# Generated by Django 5.2.4 on 2025-07-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_banners', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SideBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_banners', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='image')),
                ('url', models.URLField(blank=True, null=True, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordering')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('site_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_banners', to='core.sitesettings')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
