# Generated by Django 5.2.4 on 2025-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='It is preferable to leave this field blank so that it will be filled in automatically.', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
