# Generated by Django 5.2.4 on 2025-07-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='It is preferable to leave this field blank so that it will be filled in automatically.', max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
