# Generated by Django 5.2.4 on 2025-07-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_coupon_cart_session_key_and_more'),
        ('products', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='feature_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.featureoption', verbose_name='feature option'),
            preserve_default=False,
        ),
    ]
