# Generated by Django 5.2.4 on 2025-07-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_color_remove_cartitem_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='feature_option',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=10, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=55, verbose_name='size'),
        ),
    ]
