# Generated by Django 5.2.4 on 2025-07-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productspecification'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('c', 'Color'), ('s', 'Size')], max_length=1, verbose_name='feature')),
                ('value', models.CharField(max_length=155, verbose_name='value')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_options', to='products.product')),
            ],
        ),
    ]
