# Generated by Django 5.2.4 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureoption',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('black', 'مشکی'), ('white', 'سفید'), ('yellow', 'زرد'), ('orange', 'نارنجی'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('brown', 'قهوه\u200cای'), ('gray', 'خاکستری'), ('silver', 'نقره\u200cای'), ('gold', 'طلایی'), ('beige', 'بژ'), ('maroon', 'زرشکی'), ('navy', 'سرمه\u200cای'), ('teal', 'سبز آبی'), ('turquoise', 'فیروزه\u200cای'), ('cyan', 'آبی روشن'), ('magenta', 'ارغوانی'), ('lime', 'سبز لیمویی'), ('olive', 'زیتونی'), ('indigo', 'نیلی'), ('violet', 'بنفش روشن'), ('coral', 'مرجانی'), ('salmon', 'صورتی سالمونی'), ('khaki', 'کاکی'), ('mint', 'نعنایی'), ('peach', 'هلوئی'), ('ivory', 'عاجی'), ('lavender', 'اسطوخودوسی')], max_length=10, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='featureoption',
            name='value',
            field=models.CharField(blank=True, max_length=55, verbose_name='value'),
        ),
    ]
